:: Install dependencies with Conan 2
:: - Output files to the "build" folder
:: - Build missing packages from source if not found
:: - Use the "debug" Conan profile
:: - Set the C++ standard to C++17 for all dependencies
conan install . --build=missing -pr=debug 

:: Configure the CMake project using the toolchain file generated by Conan
:: - "conan-default" is the preset created by Conan during install
cmake --preset=conan-default

:: Build the project using the "conan-debug" preset generated by Conan
cmake --build --preset=conan-debug
